# Masterdata 主数据服务 Docker 配置
spring:
  redis:
    database: 1
    host: ${REDIS_HOST:datax-redis}
    port: 6379
    password: 1234@abcd
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://${MYSQL_HOST:datax-mysql}:3306/data_cloud?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: root
          password: 1234@abcd

security:
  oauth2:
    client:
      access-token-uri: http://datax-gateway:8612/auth/oauth/token
      user-authorization-uri: http://datax-gateway:8612/auth/oauth/authorize
      client-id: datax
      client-secret: 123456
      scope: all
    resource:
      loadBalanced: true
      token-info-uri: http://datax-gateway:8612/auth/oauth/check_token

swagger:
  enable: true
  title: 主数据API接口文档
  description: Api Documentation
  version: 1.0.0
  basePackage: cn.datax.service.data.masterdata.controller
